import type { Collection } from "@/lib/types";

/** 32 wholesale product images supplied by client */
export const PRODUCTS: Collection[] = [
  {
    id: "teardrop-drop-earrings",
    name: "Teardrop Gold Drop Earrings",
    description: "Minimal open-frame teardrop earrings with polished gold bead detail - ideal for daily wear wholesale.",
    image: "/images/products/product-01.webp",
    category: "earrings",
  },
  {
    id: "curved-diamond-pendant",
    name: "Curved Diamond Pendant Necklace",
    description: "Fine gold chain with a graceful curved bar pendant and brilliant-cut centre stone.",
    image: "/images/products/product-02.webp",
    category: "pendants",
  },
  {
    id: "halo-teardrop-earrings",
    name: "Halo Teardrop Drop Earrings",
    description: "Elegant drop earrings with stone-set teardrop frames and suspended centre stones.",
    image: "/images/products/product-03.webp",
    category: "earrings",
  },
  {
    id: "solitaire-band-couple-set",
    name: "Solitaire & Band Couple Set",
    description: "Yellow gold solitaire engagement ring paired with a brushed diamond wedding band.",
    image: "/images/products/product-04.webp",
    category: "rings",
  },
  {
    id: "classic-polished-bangles",
    name: "Classic Polished Gold Bangles",
    description: "Timeless smooth tubular gold bangles - a wholesale essential for every retail counter.",
    image: "/images/products/product-05.webp",
    category: "bangles",
  },
  {
    id: "faceted-bead-necklace",
    name: "Faceted Bead Station Necklace",
    description: "Delicate gold chain with diamond-cut and polished bead stations for everyday elegance.",
    image: "/images/products/product-06.webp",
    category: "necklaces",
  },
  {
    id: "emerald-teardrop-pendant",
    name: "Emerald Teardrop Pendant",
    description: "Statement pear-cut emerald pendant framed with brilliant stones on a fine gold chain.",
    image: "/images/products/product-07.webp",
    category: "pendants",
  },
  {
    id: "bypass-couple-ring-set",
    name: "Bypass Solitaire Couple Ring Set",
    description: "Twisted bypass solitaire with pavé accents, paired with a modern brushed signet band.",
    image: "/images/products/product-08.webp",
    category: "rings",
  },
  {
    id: "floral-engraved-bangles",
    name: "Floral Engraved Gold Bangles",
    description: "Traditional floral and vine motif bangles with beaded borders - heritage wholesale favourite.",
    image: "/images/products/product-09.webp",
    category: "bangles",
  },
  {
    id: "ruby-pearl-choker",
    name: "Ruby Pearl Statement Choker",
    description: "Ornate multi-row gold choker with pear-shaped ruby centre and pearl drop.",
    image: "/images/products/product-10.webp",
    category: "bridal",
  },
  {
    id: "geometric-rhombus-earrings",
    name: "Geometric Rhombus Drop Earrings",
    description: "Contemporary gold rhombus drops with clear stone accents - modern retail appeal.",
    image: "/images/products/product-11.webp",
    category: "earrings",
  },
  {
    id: "mens-octagon-signet",
    name: "Men's Octagon Diamond Signet",
    description: "Architectural brushed gold signet with recessed diamond - premium men's wholesale line.",
    image: "/images/products/product-12.webp",
    category: "rings",
  },
  {
    id: "floral-halo-diamond-ring",
    name: "Floral Halo Diamond Ring",
    description: "Blooming floral halo centre with twisted pavé shank - bridal and occasion wear.",
    image: "/images/products/product-13.webp",
    category: "rings",
  },
  {
    id: "lakshmi-peacock-haar",
    name: "Lakshmi Peacock Temple Haar",
    description: "Antique-finish temple necklace with Goddess Lakshmi, peacocks, rubies and pearl fringe.",
    image: "/images/products/product-14.webp",
    category: "temple",
  },
  {
    id: "split-shank-solitaire",
    name: "Split Shank Solitaire Ring",
    description: "Six-prong solitaire on a diamond-lined split shank - classic bridal bestseller.",
    image: "/images/products/product-15.webp",
    category: "rings",
  },
  {
    id: "antique-lakshmi-temple-haar",
    name: "Antique Lakshmi Temple Necklace",
    description: "Wide temple haar with matte gold relief, rubies, emeralds and hanging gold drops.",
    image: "/images/products/product-16.webp",
    category: "temple",
  },
  {
    id: "ruby-chandbali-mangalsutra",
    name: "Ruby Chandbali Mangalsutra",
    description: "Crescent pendant mangalsutra with ruby centre, pearls and black bead cord.",
    image: "/images/products/product-17.webp",
    category: "mangalsutras",
  },
  {
    id: "diamond-halo-bypass-ring",
    name: "Diamond Halo Bypass Ring",
    description: "Yellow gold bypass ring with brilliant centre stone and diamond halo.",
    image: "/images/products/product-18.webp",
    category: "rings",
  },
  {
    id: "rose-gold-wave-ring-pair",
    name: "Rose & Yellow Gold Ring Pair",
    description: "Delicate rose-gold wave solitaire paired with a geometric yellow gold diamond band.",
    image: "/images/products/product-19.webp",
    category: "rings",
  },
  {
    id: "mens-brushed-signet-ring",
    name: "Men's Brushed Diamond Signet",
    description: "Square brushed face with centre diamond and grooved shoulders - men's statement ring.",
    image: "/images/products/product-20.webp",
    category: "rings",
  },
  {
    id: "figaro-gold-chain",
    name: "Figaro Gold Chain",
    description: "Polished figaro-link yellow gold chain - high-demand wholesale staple.",
    image: "/images/products/product-21.webp",
    category: "chains",
  },
  {
    id: "chandbali-jhumka-earrings",
    name: "Chandbali Jhumka Earrings",
    description: "Three-tier traditional jhumkas with green and red gemstone accents.",
    image: "/images/products/product-22.webp",
    category: "earrings",
  },
  {
    id: "teardrop-loop-pendant",
    name: "Teardrop Loop Diamond Pendant",
    description: "Pear-loop pendant with pavé stones and suspended brilliant centre on fine chain.",
    image: "/images/products/product-23.webp",
    category: "pendants",
  },
  {
    id: "paisley-mangalsutra",
    name: "Paisley Motif Mangalsutra",
    description: "Gold paisley pendant mangalsutra with ruby centre on classic black bead chain.",
    image: "/images/products/product-24.webp",
    category: "mangalsutras",
  },
  {
    id: "popcorn-gold-chain",
    name: "Popcorn Weave Gold Chain",
    description: "Textured popcorn/wheat-link gold chain - lightweight daily wear wholesale.",
    image: "/images/products/product-25.webp",
    category: "chains",
  },
  {
    id: "lakshmi-temple-pendant-haar",
    name: "Lakshmi Temple Pendant Haar",
    description: "Matte temple necklace with seated Lakshmi pendant, rubies and gold bead fringe.",
    image: "/images/products/product-26.webp",
    category: "temple",
  },
  {
    id: "box-link-gold-chain",
    name: "Box Link Gold Chain",
    description: "Smooth Venetian box-link yellow gold chain with premium polished finish.",
    image: "/images/products/product-27.webp",
    category: "chains",
  },
  {
    id: "rope-gold-chain",
    name: "Rope Twist Gold Chain",
    description: "Classic rope-link yellow gold chain with lobster clasp - versatile wholesale piece.",
    image: "/images/products/product-28.webp",
    category: "chains",
  },
  {
    id: "floral-temple-mangalsutra",
    name: "Floral Temple Mangalsutra",
    description: "Circular floral temple pendant mangalsutra with ruby, emerald and black beads.",
    image: "/images/products/product-29.webp",
    category: "mangalsutras",
  },
  {
    id: "floral-ruby-mangalsutra",
    name: "Floral Ruby Mangalsutra",
    description: "Crescent floral pendant with ruby and clear stone on ornate black-and-gold bead chain.",
    image: "/images/products/product-30.webp",
    category: "mangalsutras",
  },
  {
    id: "curved-heart-pendant",
    name: "Curved Heart Diamond Pendant",
    description: "Horizontal curved bar pendant with pavé stones, centre brilliant and gold heart charm.",
    image: "/images/products/product-31.webp",
    category: "pendants",
  },
  {
    id: "crescent-velvet-mangalsutra",
    name: "Crescent Diamond Mangalsutra",
    description: "Elegant crescent engraved mangalsutra with centre stone, styled for bridal retail.",
    image: "/images/products/product-32.webp",
    category: "mangalsutras",
  },
];

export const PRODUCT_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "chains", label: "Chains" },
  { id: "necklaces", label: "Necklaces" },
  { id: "mangalsutras", label: "Mangalsutras" },
  { id: "earrings", label: "Earrings" },
  { id: "rings", label: "Rings" },
  { id: "bangles", label: "Bangles" },
  { id: "pendants", label: "Pendants" },
  { id: "bridal", label: "Bridal" },
  { id: "temple", label: "Temple" },
] as const;

export const FEATURED_PRODUCT_IDS = [
  "classic-polished-bangles",
  "ruby-pearl-choker",
  "floral-halo-diamond-ring",
  "lakshmi-peacock-haar",
  "chandbali-jhumka-earrings",
  "figaro-gold-chain",
] as const;
